name: DataBase
on: 
  - workflow_call
  - workflow_dispatch
jobs:
  database:
    runs-on: self-hosted
    steps:
      - name: Create Network
        run: |
          if docker network ls --format '{{ .Name }}' | grep -wq lmsnetwork; then
            echo " lms network exists "
          else
            docker network create lmsnetwork
          fi
      - name: check weather the db container exists or not
        run: |
         if docker ps -a --format '{{ .Names }}' | grep -wq lmsdb; then
           echo "lms db exists"
         else
           docker container run -dt --name lmsdb --network lmsnetwork -p 5432:5432 -e POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD}} postgres
         fi  
